name: manga_easy_persistent_database_service
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.1

dependencies:
  path: ^1.8.3
  path_provider: ^2.0.15
  sembast: ^3.4.4
  uuid: ^3.0.7

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
